/**
 * src/seeds/seed.products.ts
 * ─────────────────────────
 * Seeds categories + products from clean-updated-local.json
 * (generated by image_downloader.py).
 *
 * Run:
 *   npx ts-node src/seeds/seed.products.ts
 *
 * The script is IDEMPOTENT: it skips rows whose slug already exists.
 *
 * Prerequisites:
 *   1. Tables created  →  run  src/database/migrations/001_create_tables.sql
 *   2. Images downloaded →  run  python src/seeds/image_downloader.py
 */
import 'dotenv/config'; 
import path from 'path';
import fs   from 'fs';
import pool from '../database/connection';

// ── JSON shape ────────────────────────────────────────────────────────────────
interface RawProduct {
  title:         string;
  reference:     string | null;
  priceHT:       string | null;
  images:        string[];
  description:   string | null;
  dimensions:    Record<string, string> | null;
  categories:    string[];           // [cat, subcat, subsubcat]
  theme:         string | null;
  is_in_variant: boolean;
  variant_id:    string | null;
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .substring(0, 255);
}

function makeUniqueSlug(base: string, used: Set<string>): string {
  let slug    = slugify(base);
  let attempt = slug;
  let n       = 1;
  while (used.has(attempt)) attempt = `${slug}-${n++}`;
  used.add(attempt);
  return attempt;
}

// ── Category upsert ───────────────────────────────────────────────────────────
// Cache: "name|||parentId"  →  DB id
const catCache = new Map<string, number>();

async function upsertCategory(
  name:     string,
  parentId: number | null,
  depth:    number,
  slugSet:  Set<string>
): Promise<number> {
  const key = `${name}|||${parentId ?? 'ROOT'}`;
  if (catCache.has(key)) return catCache.get(key)!;

  // <=> is NULL-safe equals in MariaDB/MySQL
  const [rows] = await pool.query<any[]>(
    'SELECT id FROM categories WHERE name = ? AND (parentId <=> ?)',
    [name, parentId]
  );
  if (rows[0]) {
    catCache.set(key, rows[0].id);
    return rows[0].id;
  }

  const slug = makeUniqueSlug(name, slugSet);
  const [res] = await pool.query<any>(
    'INSERT INTO categories (name, slug, parentId, depth) VALUES (?, ?, ?, ?)',
    [name, slug, parentId, depth]
  );
  catCache.set(key, res.insertId);
  return res.insertId;
}

// ── Main ──────────────────────────────────────────────────────────────────────
async function seed() {
  const jsonPath = path.join(__dirname, 'clean-updated-local.json');
  if (!fs.existsSync(jsonPath)) {
    console.error(`ERROR: ${jsonPath} not found.\nRun image_downloader.py first.`);
    process.exit(1);
  }

  const products: RawProduct[] = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  console.log(`Loaded ${products.length} products`);

  // Pre-load existing slugs
  const catSlugSet  = new Set<string>();
  const prodSlugSet = new Set<string>();

  const [existingCats]  = await pool.query<any[]>('SELECT slug FROM categories');
  const [existingProds] = await pool.query<any[]>('SELECT slug FROM products');
  for (const r of existingCats)  catSlugSet.add(r.slug);
  for (const r of existingProds) prodSlugSet.add(r.slug);

  let inserted = 0;
  let skipped  = 0;

  for (const raw of products) {
    // ── 1. Resolve 3-level category ───────────────────────────────────────
    //   categories[0] = category      depth 0
    //   categories[1] = subcategory   depth 1
    //   categories[2] = subsubcat     depth 2  ← leafCategoryId stored on product
    const cats = raw.categories ?? [];
    let leafCategoryId: number | null = null;

    if (cats.length > 0) {
      const lvl0id = await upsertCategory(cats[0], null,   0, catSlugSet);

      if (cats.length > 1) {
        const lvl1id = await upsertCategory(cats[1], lvl0id, 1, catSlugSet);

        if (cats.length > 2) {
          leafCategoryId = await upsertCategory(cats[2], lvl1id, 2, catSlugSet);
        } else {
          leafCategoryId = lvl1id;
        }
      } else {
        leafCategoryId = lvl0id;
      }
    }

    // ── 2. Skip duplicate products ────────────────────────────────────────
    const baseSlug = slugify(raw.title);
    if (prodSlugSet.has(baseSlug)) { skipped++; continue; }
    const slug = makeUniqueSlug(raw.title, prodSlugSet);

    const price      = raw.priceHT ? parseFloat(raw.priceHT) : null;
    const images     = (raw.images ?? []).filter(
      (u: string) => u.startsWith('/uploads') || u.startsWith('http')
    );
    const dimensions = raw.dimensions && Object.keys(raw.dimensions).length > 0
      ? raw.dimensions : null;

    // ── 3. Insert product ─────────────────────────────────────────────────
    await pool.query(
      `INSERT INTO products
         (title, slug, reference, description, price, discountPercent,
          images, inStock, categoryId, dimensions, isInVariant, variantId)
       VALUES (?, ?, ?, ?, ?, 0, ?, 1, ?, ?, ?, ?)`,
      [
        raw.title,
        slug,
        raw.reference   ?? null,
        raw.description ?? null,
        price,
        JSON.stringify(images),
        leafCategoryId,
        dimensions ? JSON.stringify(dimensions) : null,
        raw.is_in_variant ? 1 : 0,
        raw.variant_id    ?? null,
      ]
    );

    inserted++;
    if ((inserted + skipped) % 100 === 0) {
      console.log(`  … ${inserted} inserted, ${skipped} skipped`);
    }
  }

  console.log(`\n✓ Seed complete — inserted: ${inserted}, skipped: ${skipped}`);
  await pool.end();
}

seed().catch(err => {
  console.error('Seed failed:', err);
  pool.end().finally(() => process.exit(1));
});